configurations:
  - sources:
      - ./LikePicsKit/Sources/Domain
    templates:
      - ./templates
    output:
      ./LikePicsKit/Sources/TestHelper/Mocks/Struct/Domain.AutoDefaultValue.generated.swift
    args:
      testable_import: "Domain"
  - sources:
      - ./LikePicsKit/Sources/Persistence
    templates:
      - ./templates
    output:
      ./LikePicsKit/Sources/TestHelper/Mocks/Struct/Persistence.AutoDefaultValue.generated.swift
    args:
      testable_import: "Persistence"
  - sources:
      - ./LikePicsKit/Sources/LikePicsUIKit
    templates:
      - ./templates
    output:
      ./LikePicsKit/Sources/TestHelper/Mocks/Struct/LikePicsUIKit.AutoDefaultValue.generated.swift
    args:
      testable_import: "LikePicsUIKit"
