///
/// @Generated by Mockolo
///

import ClipCreationFeatureCore
import Combine
import Common
import CompositeKit
import Domain
import Environment
import Foundation
import LikePicsUIKit
import Smoothie
import UIKit

@testable import ClipCreationFeature

public class ClipStorableMock: ClipStorable {
    public init() {}

    public private(set) var createCallCount = 0
    public var createHandler: ((ClipRecipe, [ImageContainer], Bool) -> (Result<Clip.Identity, ClipStorageError>))?
    public func create(clip: ClipRecipe, withContainers containers: [ImageContainer], forced: Bool) -> Result<Clip.Identity, ClipStorageError> {
        createCallCount += 1
        if let createHandler = createHandler {
            return createHandler(clip, containers, forced)
        }
        fatalError("createHandler returns can't have a default value thus its handler must be set")
    }
}
