# vim: syntax=ruby

force(true)
submit_for_review(false)
automatic_release(false)

skip_binary_upload(true)
skip_metadata(false)
skip_screenshots(false)
skip_app_version_update(false)

overwrite_screenshots(true)

# AppStoreConnectAPI非対応項目を設定
# https://zenn.dev/moga/articles/752b5f5a8fc001060d1a
precheck_include_in_app_purchases(false)

