fastlane_require "dotenv"

Dotenv.load(".env.secret")

default_platform(:ios)

platform :ios do
  lane :test do
    scan
  end

  lane :take_snapshots do
    snapshot
  end

  lane :update_development_pp do
    match
  end

  lane :update_appstore_pp do
    match
  end

  lane :release do
    app_store_connect_api_key
    deliver
  end

  lane :release_build_only do
    app_store_connect_api_key
    match
    gym
    pilot
    clean_build_artifacts
  end
end

platform :mac do
  lane :update_development_pp do
    match
  end

  lane :update_appstore_pp do
    match
  end
end
