fastlane_require "dotenv"

Dotenv.load(".env.secret")

default_platform(:ios)

platform :ios do
  lane :test do
    scan
  end

  lane :take_snapshots do
    snapshot
  end

  lane :release do
    app_store_connect_api_key
    build_for_appstore
    github_release
    deliver
    clean_build_artifacts
  end

  lane :release_build_only do
    app_store_connect_api_key
    build_for_appstore
    pilot
    clean_build_artifacts
  end

  private_lane :build_for_appstore do
    match
    gym
  end

  private_lane :github_release do
    get_version_number
    changelog_from_git_commits
    set_github_release(
      name: "#{lane_context[SharedValues::VERSION_NUMBER]}",
      tag_name: "v#{lane_context[SharedValues::VERSION_NUMBER]}",
      description: lane_context[SharedValues::FL_CHANGELOG],
      upload_assets: [
        lane_context[SharedValues::IPA_OUTPUT_PATH],
        lane_context[SharedValues::DSYM_OUTPUT_PATH],
      ]
    )
  end
end
