devices([
  "iPhone 13 Pro Max",
  "iPhone 8 Plus",
  "iPad Pro (12.9-inch) (2nd generation)",
  "iPad Pro (12.9-inch) (4th generation)",
])

languages([
  "en-US",
  "ja",
])

project("./Snapshot/Snapshot.xcodeproj")
scheme("SnapshotUITests")

output_directory("./fastlane/screenshots")

clear_previous_screenshots(true)

override_status_bar(true)

stop_after_first_error(true)

