devices([
  "iPhone 8",
])

languages([
  "en-US",
  "ja-JP",
])

ENV["FASTLANE_SNAPSHOT"] = "YES"
launch_arguments([
  "-FASTLANE_SNAPSHOT YES"
])

scheme("SnapshotHelper")

output_directory("./fastlane/screenshots")

clear_previous_screenshots(true)

override_status_bar(true)

