devices([
  "iPhone 12 Pro Max",
  "iPhone 8 Plus",
  "iPad Pro (12.9-inch) (2nd generation)",
  "iPad Pro (12.9-inch) (3rd generation)",
])

languages([
  "en-US",
  "ja",
])

scheme("SnapshotHelper")

output_directory("./fastlane/screenshots")

clear_previous_screenshots(true)

override_status_bar(true)

stop_after_first_error(true)

